
[build]
builder = "nixpacks"
buildCommand = "cd backend-app && cargo build --release"

[deploy]
startCommand = "cd backend-app && ./target/release/backend-app"
healthCheckPath = "/api/health"
healthCheckTimeout = 30

[[services]]
name = "backend"
[[services.ports]]
port = 5000